#pragma once


#define OLED_DISPLAY_128X64
#define OLED_TIMEOUT 0          
#define OLED_UPDATE_INTERVAL 16  


#define RGB_MATRIX_LED_COUNT 77
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_KEYPRESSES         
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define ENABLE_RGB_MATRIX_SOLID_COLOR
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 180
#define RGB_MATRIX_SPLASH_SPEED_MAX 200 


#define COMBO_COUNT 1
